[package]
name = "seed"
version = "0.4.0"
description = "A Rust framework for creating web apps, using WebAssembly"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
license = "MIT"
repository = "https://www.github.com/David-OConnor/seed"
homepage = "https://seed-rs.org"
documentation = "https://docs.rs/seed"
readme = "README.md"
keywords = ["wasm", "webassembly", "frontend", "framework", "web"]
categories = ["wasm", "web-programming"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
wasm-bindgen-test = "0.2.45" # NOTE: keep in sync with wasm-bindgen version

[dependencies]
console_error_panic_hook = "^0.1.6"
enclose = "1.1.6"
futures = "^0.1.27"
# Can't use repo with a release.
#gloo-timers = { path = "vendor/gloo_timers", features = ["futures"] }
#gloo-timers = { git = "https://github.com/rustwasm/gloo", features = ["futures"] }
indexmap = "1.0.2"
js-sys = "0.3.22"
pulldown-cmark = "^0.5.2"
serde = { version = "^1.0.92", features = ['derive'] }
serde_json = "^1.0.39"
# NOTE: keep in sync with wasm-bindgen-test version
wasm-bindgen = {version = "0.2.45", features = ["serde-serialize"]}
wasm-bindgen-futures = "^0.3.22"

[dependencies.web-sys]
version = "0.3.22"
features = [
    "AbortController",
    "AbortSignal",
    "CustomEvent",
    "CustomEventInit",
    "Document",
    "DomException",
    "Element",
    "Event",
    "EventTarget",
    "Headers",
    "History",
    "HtmlElement",
    "HtmlCollection",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "HtmlButtonElement",
    "Location",
    "MouseEvent",
    "Node",
    "NodeList",
    "Performance",
    "PointerEvent",
    "PopStateEvent",
    "ReferrerPolicy",
    "Request",
    "RequestCache",
    "RequestCredentials",
    "RequestInit",
    "RequestMode",
    "RequestRedirect",
    "Response",
    "Storage",
    "Text",
    "console",
    "Window",
    "KeyboardEvent",
    "InputEvent",
]

[workspace]
members = [
    "examples/animation_frame",
    "examples/counter",
    # "examples/homepage",   # isn't Rust project
    "examples/mathjax",
    "examples/orders",
    # "examples/server_integration",   # has own workspace
    "examples/server_interaction",
#    "examples/server_interaction_detailed",  # has own workspace
    "examples/todomvc",
    "examples/update_from_js",
    "examples/websocket",
    "examples/window_events",
]

exclude = [
    # it has own workspace
    "examples/server_integration",
    "examples/server_interaction_detailed",
    "vendor/gloo_timers",  # temporary until released
]
