[package]
name = "websocket"
version = "0.1.0"
authors = ["Markus Kohlhase <markus.kohlhase@slowtec.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
# common
serde = { version = "^1.0.92", features = ["derive"] }
serde_json = "^1.0.39"

# server
ws = { version = "0.8.1", optional = true }

#client
seed = { path = "../../", optional = true }
wasm-bindgen = { version = "^0.2.45", optional = true }
[dependencies.web-sys]
version = "^0.3.22"
features = ["WebSocket", "MessageEvent"]
optional = true

[features]
default = []
client = ["seed", "wasm-bindgen", "web-sys"]
server = ["ws"]

